- hosts: terraform-ansible #qual host queremos acessar
  tasks: #Quais tarefas serão executadas nesse host
    - name: Instalando python3, virtualenv e o nmap
      apt: #gerenciador de pacotes (gerais não só ubuntu)
        pkg: 
          - python3
          - virtualenv
          - nmap
        update_cache: yes #atualiza o cache de pacotes
      become: true #para executar como root
    
    - name: Instalando dependencias com pip (Django e Django Rest)
      pip:
        virtualenv: /home/ubuntu/teste/venv #caminho da virtualenv
        name:
          - django
          - djangorestframework
    # Possibilitando a idenpotencia
    - name: Verificando se o projeto já existe
      stat: #verifica se o arquivo existe
        path: /home/ubuntu/teste/setup/settings.py
      register: projeto #salva o resultado da verificação em uma variável

    - name: Iniciando o projeto
      shell: |
        source /home/ubuntu/teste/venv/bin/activate
        django-admin startproject setup /home/ubuntu/teste
      when: not projeto.stat.exists
      args: #Garantindo que o comando será executado no bash
        executable: /bin/bash

    - name: Alterando o hosts do settings
      lineinfile: #altera uma linha do arquivo
        path: /home/ubuntu/teste/setup/settings.py #arquivo que será alterado
        regexp: '^ALLOWED_HOSTS' #expressão regular para encontrar a linha
        line: 'ALLOWED_HOSTS = ["*"]' # linha que será inserida
        backrefs: yes # para que o ansible caso não encontre a linha, não insira nada